# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Angular CI

on:
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  build:

    runs-on: self-hosted # Specifies that the job should run on a self-hosted runner

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      working-directory: ./hello-world-project # Adjust this to the actual path of your project directory

    - name: Build the Angular application
      run: npm run build
      working-directory: ./hello-world-project # Adjust this to the actual path of your project directory

    - name: Run tests
      run: npm test
      working-directory: ./hello-world-project # Adjust this to the actual path of your project directory

