name: Angular CI

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: self-hosted 
    strategy:
      matrix:
        node-version: [18, 20]
        
    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: hello-world-project/package-lock.json

    - name: Install dependencies
      run: npm ci
      working-directory: ./hello-world-project 

    - name: Build the Angular application
      run: npm run build --if-present
      working-directory: ./hello-world-project
